PO_Doubler_fulfills_D_cbmc:
	cbmc --unwind 10 po_PO_Doubler_fulfills_D.c
PO_Doubler_fulfills_D_seahorn:
	seahorn --unwind 10 po_PO_Doubler_fulfills_D.c
PO_Doubler_fulfills_D_cpachecker:
	cpachecker --unwind 10 po_PO_Doubler_fulfills_D.c
