name: Tests

on:
    workflow_dispatch:
    push:
    pull_request:
        branches:
            - "main"
    merge_group:

permissions:
    contents: read


jobs:
    unit-tests:
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, windows-latest ]
                java: [ 21 ]
        continue-on-error: false
        runs-on: ${{ matrix.os }}
        env:
            GH_TOKEN: ${{ github.token }}
        steps:
            -   uses: actions/checkout@v5
            -   name: Set up JDK 21
                uses: actions/setup-java@v5
                with:
                    java-version: ${{ matrix.java }}
                    distribution: 'corretto'
                    cache: 'gradle'

            -   name: Set up Gradle
                uses: gradle/actions/setup-gradle@v4

            -   run: ./gradlew testClasses
            -   run: ./gradlew testClasses

            -   name: Setup nuXmv
                uses: verifaps/setup-nuxmv@v0.1.2

            -   name: Test nuXmv
                run: echo "quit" | nuXmv -int | head -n 1

            -   name: setup-smt
                uses: keyproject/setup-smt@v0.2.0

            -   name: Test z3
                run: z3 -version

            -   run: ./gradlew test --continue --no-problems-report

            -   name: Upload test results
                uses: actions/upload-artifact@v4.6.2
                if: success() || failure()
                with:
                    name: test-results-${{matrix.os}}-${{matrix.java}}
                    path: |
                        **/build/test-results/*/*.xml
                        **/build/reports/
                        !**/jacocoTestReport.xml

            -   name: Upload coverage reports to Codecov
                uses: codecov/codecov-action@v5

            -   name: Summarize tests results
                uses: jeantessier/test-summary-action@v1
                if: ${{ always() }}

            -   name: Build distribution
                run: ./gradlew shadowJar

    integration-test-counter:
        runs-on: ubuntu-latest
        steps:
            -   name: "Run integration test: Counter"
                run: |
                    cd examples/counter
                    java -jar ../../build/libs/cagen-1.0-all.jar -o out Counter.sys
                    cd out 
                    make

    spotless:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v5
            -   name: Set up JDK 23
                uses: actions/setup-java@v5
                with:
                    java-version: '21'
                    distribution: 'temurin'

            -   name: Set up Gradle
                uses: gradle/actions/setup-gradle@v4

            -   run: ./gradlew spotlessCheck
